apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-init-topics
spec:
  template:
    spec:
      containers:
      - name: init-topics
        image: confluentinc/cp-kafka:latest
        command:
        - /bin/bash
        - -c
        - |
          echo "Waiting for Kafka to be ready..."
          sleep 15
          kafka-topics --bootstrap-server kafka:9092 --delete --topic dados-sensores
          kafka-topics --bootstrap-server kafka:9092 --delete --topic comandos-fabrica
          echo "Topics deleted."
          kafka-topics --create --bootstrap-server kafka:9092 --topic dados-sensores --partitions 6 --replication-factor 3
          kafka-topics --create --bootstrap-server kafka:9092 --topic comandos-fabrica --partitions 6 --replication-factor 3
          echo "Topics created."
      restartPolicy: OnFailure
