apiVersion: v1
kind: ConfigMap
metadata:
  name: adminer-autologin
data:
  index.php: |
    <?php
    // Recupera variáveis injetadas pelo ConfigMap do Postgres no K8s
    $host = getenv("PG_HOST") ?: "postgres";
    $user = getenv("POSTGRES_USER") ?: "postgres";
    $pass = getenv("POSTGRES_PASSWORD") ?: "postgres";
    $db   = getenv("POSTGRES_DB") ?: "fabrica";

    // Injeção direta na query string (simula envio de formulário para auto-login no PostgreSQL)
    $_GET["pgsql"] = $host;
    $_GET["username"] = $user;
    $_GET["db"] = $db;
    
    function adminer_object() {
        class AdminerAutoLogin extends Adminer {
            function name() {
                return 'Smart Factory DB';
            }
            function credentials() {
                // Força o retorno do servidor, usuário e senha a partir do ConfigMap
                return array(getenv("PG_HOST") ?: "postgres", getenv("POSTGRES_USER") ?: "postgres", getenv("POSTGRES_PASSWORD") ?: "postgres");
            }
            function database() {
                return getenv("POSTGRES_DB") ?: "fabrica";
            }
            function login($login, $password) {
                // Pula a validação da tela de login (sempre aceita)
                return true;
            }
        }
        return new AdminerAutoLogin;
    }
    include "./adminer.php";
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: adminer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer:latest
        envFrom:
        - configMapRef:
            name: postgres-config
        env:
        - name: PG_HOST
          value: "postgres"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: autologin-script
          mountPath: /var/www/html/index.php
          subPath: index.php
      volumes:
      - name: autologin-script
        configMap:
          name: adminer-autologin
